import React from 'react'
import Button from './Button'

export default {
	One:         props => <Button value="1" keypress="1" { ...props } />,
	Two:         props => <Button value="2" keypress="2" { ...props } />,
	Three:       props => <Button value="3" keypress="3" { ...props } />,
	Four:        props => <Button value="4" keypress="4" { ...props } />,
	Five:        props => <Button value="5" keypress="5" { ...props } />,
	Six:         props => <Button value="6" keypress="6" { ...props } />,
	Seven:       props => <Button value="7" keypress="7" { ...props } />,
	Eight:       props => <Button value="8" keypress="8" { ...props } />,
	Nine:        props => <Button value="9" keypress="9" { ...props } />,
	Zero:        props => <Button value="0" keypress="0" { ...props } />,
	Dot:         props => <Button value='.' keypress="." { ...props } />,
	Pi:          props => <Button value='pi' display='&Pi;' { ...props } />,
	E:           props => <Button value='e' { ...props } />,
	Random:      props => <Button value='random' display="Rand" { ...props } />,
   
	Divide:      props => <Button value="/" display="&divide;" keypress="/" { ...props } />,
	Multiply:    props => <Button value="*" display="X" keypress="*" { ...props } />,
	Subtract:    props => <Button value="-" keypress="-" { ...props } />,
	Add:         props => <Button value="+" keypress="+" { ...props } />,
	Percent:     props => <Button value="%" { ...props } />,
	Equals:      props => <Button value="=" keypress="Enter" { ...props } />,

	C:          props => <Button value="C" keypress="Escape" { ...props } />,
	AC:          props => <Button value="AC" { ...props } />,
	Sign:        props => <Button value="+/-" { ...props } />,
	OpenParens:  props => <Button value="(" keypress="(" { ...props } />,
	CloseParens: props => <Button value=")" keypress=")" { ...props } />,
	MemAdd:      props => <Button value="M+" { ...props } tooltip="Memory Plus" />,
	MemSub:      props => <Button value="M-" { ...props } tooltip="Memory Subtract" />,
	MemRecall:   props => <Button value="MR" { ...props } tooltip="Memory Recall" />,
	MemClear:    props => <Button value="MC" { ...props } tooltip="Memory Clear" />,

	Pow:         props => <Button value="x^y" display="x<sup>y</sup>" { ...props } />,
	Square:      props => <Button value="x^2" display="x<sup>2</sup>" { ...props } />,
	Cube:        props => <Button value="x^3" display="x<sup>3</sup>" { ...props } />,
	TwoPow:      props => <Button value="2^x" display="2<sup>x</sup>" { ...props } />,
	EPow:        props => <Button value="e^x" display="e<sup>x</sup>" { ...props } />,
	TenPow:      props => <Button value="10^x" display="10<sup>x</sup>" { ...props } />,
	Invert:      props => <Button value="1/x" { ...props } />,
	Abs:         props => <Button value="abs" display="|x|" { ...props } />,
	Root:        props => <Button value="root" display="√x" { ...props } />,
	XRoot:       props => <Button value="nroot" display="<sup>x</sup>√y" { ...props } />,
	CubeRoot:    props => <Button value="3root" display="<sup>3</sup>√x" { ...props } />,
	Log:         props => <Button value="log" { ...props } />,
	LTen:        props => <Button value="lten" display="log<sub>10</sub>" { ...props } />,
	Ln:          props => <Button value="ln" { ...props } />,
	Factorial:   props => <Button value="x!" { ...props } />,

	Sin:         props => <Button value="sin" { ...props } />,
	Cos:         props => <Button value="cos" { ...props } />,
	Tan:         props => <Button value="tan" { ...props } />,
	Csc:         props => <Button value="csc" { ...props } />,
	Sec:         props => <Button value="sec" { ...props } />,
	Cot:         props => <Button value="cot" { ...props } />,

	Empty:       props => <Button value="" { ...props } />,
}
